#normal matrix setup
language: node_js

node_js:
  - node     # latest stable Node.js release
#  - lts/*    # latest LTS Node.js release

install:
  - npm install

#cache:
#  directories:
#    - "node_modules"

matrix:
  include:
#    - name: Build and run Docker image (with 'Dockerfile'), default Docker
#      language: generic
#      services:
#        - docker
#      script:
#        - docker --version
#        - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
#        - docker run -dp 1337:1337 dr4ft-app
#        - docker ps -a
#      after_script:
#        - docker images
    - name: Build and run Docker image (with 'Dockerfile'), newest Docker
      language: generic
      addons:
        apt:
          packages:
            - docker-ce
      services:
        - docker
      script:
        - docker --version
        - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
        - docker run -dp 1337:1337 dr4ft-app
        - docker ps -a
      after_script:
        - docker images

#nodejs + docker in stages setup
#jobs:
#  include:
#  - stage: Tests
#    name: Install (on latest Node.js)
#    language: node_js
#    node_js:
#       - node     # latest stable Node.js release
#    #   - lts/*    # latest LTS Node.js release
#    install:
#      - npm install
#    # script:
#    #   - npm start
#    # after_script:
#    #    - npm test
#    # cache:
#    #    directories:
#    #      - "node_modules"
#  - stage: Tests
#    name: Install (on latest Node.js LTS)
#    language: node_js
#    node_js:
#       - lts/*    # latest LTS Node.js release
#    install:
#      - npm install
#    # script:
#    #   - npm start
#    # after_script:
#    #    - npm test
#    # cache:
#    #    directories:
#    #      - "node_modules"
#  - stage: Tests
#    name: Build and run Docker image (with 'Dockerfile')
#    language: generic
#    services:
#      - docker
#    script:
#      - docker --version
#      - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
#      - docker run -dp 1337:1337 dr4ft-app
#      - docker ps -a
#    after_script:
#      - docker images
#  - stage: Tests
#    name: Build and run Docker image (with 'Dockerfile'), newest Docker
#    language: generic
#    addons:
#      apt:
#        packages:
#          - docker-ce
#    services:
#      - docker
#    script:
#      - docker --version
#      - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
#      - docker run -dp 1337:1337 dr4ft-app
#      - docker ps -a
#    after_script:
#      - docker images
