#normal matrix.include setup
matrix:
  include:
    - name: Install Node.js app on newest Node.js
      language: node_js
      node_js: node
      cache:
        directories:
          - node_modules
      install:
        - npm install
      script: skip
    - name: Install Node.js app on newest Node.js LTS
      language: node_js
      node_js: lts/*
      cache:
        directories:
          - node_modules
      install:
        - npm install
      script: skip
    - name: ESLint Check
      language: node_js
      node_js: node
      install: skip
      script:
        - npm test
  allow_failures:
    - name: ESLint

#    - name: Build and run Docker image (with 'Dockerfile') on newest Docker
#      language: generic
#      addons:
#        apt:
#          packages:
#            - docker-ce
#      services:
#        - docker
#      script:
#        - docker --version
#        - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
#        - docker run -dp 1337:1337 dr4ft-app
#        - docker ps -a
#      after_script:
#        - docker images

#-------------------------------------------------
#nodejs + docker in stages setup
#jobs:
#  include:
#  - stage: Tests
#    name: Install (on latest Node.js)
#    language: node_js
#    node_js:
#       - node     # latest stable Node.js release
#    #   - lts/*    # latest LTS Node.js release
#    install:
#      - npm install
#    # script:
#    #   - npm start
#    # after_script:
#    #    - npm test
#    # cache:
#    #    directories:
#    #      - "node_modules"
#  - stage: Tests
#    name: Install (on latest Node.js LTS)
#    language: node_js
#    node_js:
#       - lts/*    # latest LTS Node.js release
#    install:
#      - npm install
#    # script:
#    #   - npm start
#    # after_script:
#    #    - npm test
#    # cache:
#    #    directories:
#    #      - "node_modules"
#  - stage: Tests
#    name: Build and run Docker image (with 'Dockerfile')
#    language: generic
#    services:
#      - docker
#    script:
#      - docker --version
#      - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
#      - docker run -dp 1337:1337 dr4ft-app
#      - docker ps -a
#    after_script:
#      - docker images
#  - stage: Tests
#    name: Build and run Docker image (with 'Dockerfile'), newest Docker
#    language: generic
#    addons:
#      apt:
#        packages:
#          - docker-ce
#    services:
#      - docker
#    script:
#      - docker --version
#      - docker build --tag dr4ft-app .    # builds from the Dockerfile in repo root
#      - docker run -dp 1337:1337 dr4ft-app
#      - docker ps -a
#    after_script:
#      - docker images

#notifications:
#  email: false
#  webhooks:
#    urls:
#      - dr4ft gitter url here
#    on_success: change
#    on_failure: change
#    on_start: never
#    on_cancel: change
#    on_error: change
