# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ tooomm-patch-5 ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

#    - name: Use Node.js LTS    # only needed if not the default Node.js should be used
#      uses: actions/setup-node@v1
##      uses: actions/setup-node@v2    # v2 still in beta, see: https://github.com/marketplace/actions/setup-node-js-environment
#      with:
#        node-version: 12.x

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

#    - name: Run app
#      run: npm start

    - name: Run test
      run: npm test

    - name: Run lint
      run: npm run lint
