# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ tooomm-patch-5 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
#      uses: actions/setup-node@v2    # v2 still in beta, see: https://github.com/marketplace/actions/setup-node-js-environment

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Run app
      run: npm start

    - name: Run test
      run: npm test

    - name: Run lint
      run: npm run lint
